# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\synchronizeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
from functools import partial

# TODO Indicate which data User is selecting for synchronize e.g song, album, playlist, author
class synchronizeDialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__()
        if parent:
            self.setParent(parent)
        self.setupUi(self)
        self.synchronizeDialogSongsQPushButton.clicked.connect(partial(self.set_synchronize_dialog_stacked_widget_index, 0))
        self.synchronizeDialogAlbumsQPushButton.clicked.connect(partial(self.set_synchronize_dialog_stacked_widget_index, 1))
        self.synchronizeDialogPlaylistsQPushButton.clicked.connect(partial(self.set_synchronize_dialog_stacked_widget_index, 2))
        self.synchronizeDialogAuthorsQPushButton.clicked.connect(partial(self.set_synchronize_dialog_stacked_widget_index, 3))


    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(524, 485)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(524, 485))
        Dialog.setMaximumSize(QtCore.QSize(524, 485))
        Dialog.setStyleSheet("border: none;\n"
                             "color:  white;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(524, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(524, 485))
        self.frame_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.frame_3.setStyleSheet("#frame_7{\n"
                                   "    border-bottom: 1px solid rgba(179, 179, 179, 0.25);\n"
                                   "}\n"
                                   "#frame_7 QPushButton{\n"
                                   "    color: rgb(179, 179, 179);\n"
                                   "    font: 57 10pt \"Heebo Medium\";\n"
                                   "    border-bottom: 2px solid transparent;\n"
                                   "}\n"
                                   "#frame_7 QPushButton:hover:!checked{\n"
                                   "    color: white;\n"
                                   "}\n"
                                   "#frame_7 QPushButton:checked{\n"
                                   "    border-bottom: 2px solid rgb(247, 178, 158);\n"
                                   "    color: white;\n"
                                   "}\n"
                                   "#frame_3{\n"
                                   "    border-radius: 8px;\n"
                                   "    background-color: rgb(40, 40, 40);\n"
                                   "}\n"
                                   "#synchronizeDialogExitButton{\n"
                                   "    background-color: none;\n"
                                   "    border-radius: 16px;\n"
                                   "}\n"
                                   "#synchronizeDialogExitButton:hover{\n"
                                   "    background-color: rgba(179, 179, 179, 0.25);\n"
                                   "}\n"
                                   "#synchronizeDialogExitButton:pressed{\n"
                                   "    background-color: rgba(179, 179, 179, 0.35);\n"
                                   "}\n"
                                   "#label{\n"
                                   "    color: white;\n"
                                   "    font: 87 17pt \"Heebo Black\";\n"
                                   "}\n"
                                   "#synchronizeDialogSynchronizeButton{\n"
                                   "    border-radius: 16px;\n"
                                   "    background-color: white;\n"
                                   "    color: black;\n"
                                   "    font: 87 9pt \"Heebo Medium\";\n"
                                   "}\n"
                                   "QScrollBar:vertical {\n"
                                   "    width: 12px;\n"
                                   "    background: transparent;\n"
                                   "}\n"
                                   "QScrollBar::handle:vertical{\n"
                                   "    background: rgb(179, 179, 179, 0.45);\n"
                                   "}\n"
                                   "QScrollBar::handle:hover:vertical{\n"
                                   "    background: rgb(179, 179, 179, 0.55);\n"
                                   "}\n"
                                   "QScrollBar::sub-page:vertical{\n"
                                   "    background: transparent;\n"
                                   "}\n"
                                   "QScrollBar::add-page:vertical{\n"
                                   "    background: transparent;\n"
                                   "}\n"
                                   "\n"
                                   "QScrollBar::add-line:vertical{\n"
                                   "    widgth: 0px;\n"
                                   "    height: 0px;\n"
                                   "    background: none;\n"
                                   "    border: none;\n"
                                   "}\n"
                                   "QScrollBar::sub-line:vertical{\n"
                                   "    widgth: 0px;\n"
                                   "    height: 0px;\n"
                                   "    border: none;\n"
                                   "    background: none;\n"
                                   "}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(24, 24, 24, 24)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("Synchronize data")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout.addWidget(self.frame_4)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.synchronizeDialogExitButton = QtWidgets.QPushButton(self.frame_5)
        self.synchronizeDialogExitButton.setMinimumSize(QtCore.QSize(32, 32))
        self.synchronizeDialogExitButton.setMaximumSize(QtCore.QSize(32, 32))
        self.synchronizeDialogExitButton.setStyleSheet("")
        self.synchronizeDialogExitButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/48x48/outlined/icons/48x48/outlined/outline_close_white_48dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.synchronizeDialogExitButton.setIcon(icon)
        self.synchronizeDialogExitButton.setIconSize(QtCore.QSize(20, 20))
        self.synchronizeDialogExitButton.setObjectName("synchronizeDialogExitButton")
        self.verticalLayout_4.addWidget(self.synchronizeDialogExitButton)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout_11.addWidget(self.frame)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 33))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 33))
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(24)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.synchronizeDialogSongsQPushButton = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.synchronizeDialogSongsQPushButton.sizePolicy().hasHeightForWidth())
        self.synchronizeDialogSongsQPushButton.setSizePolicy(sizePolicy)
        self.synchronizeDialogSongsQPushButton.setMinimumSize(QtCore.QSize(0, 33))
        self.synchronizeDialogSongsQPushButton.setMaximumSize(QtCore.QSize(16777215, 33))
        self.synchronizeDialogSongsQPushButton.setText("Songs")
        self.synchronizeDialogSongsQPushButton.setCheckable(True)
        self.synchronizeDialogSongsQPushButton.setChecked(True)
        self.synchronizeDialogSongsQPushButton.setAutoExclusive(True)
        self.synchronizeDialogSongsQPushButton.setObjectName("synchronizeDialogSongsQPushButton")
        self.horizontalLayout_4.addWidget(self.synchronizeDialogSongsQPushButton)
        self.synchronizeDialogAlbumsQPushButton = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.synchronizeDialogAlbumsQPushButton.sizePolicy().hasHeightForWidth())
        self.synchronizeDialogAlbumsQPushButton.setSizePolicy(sizePolicy)
        self.synchronizeDialogAlbumsQPushButton.setMinimumSize(QtCore.QSize(0, 33))
        self.synchronizeDialogAlbumsQPushButton.setMaximumSize(QtCore.QSize(16777215, 33))
        self.synchronizeDialogAlbumsQPushButton.setText("Albums")
        self.synchronizeDialogAlbumsQPushButton.setCheckable(True)
        self.synchronizeDialogAlbumsQPushButton.setAutoExclusive(True)
        self.synchronizeDialogAlbumsQPushButton.setObjectName("synchronizeDialogAlbumsQPushButton")
        self.horizontalLayout_4.addWidget(self.synchronizeDialogAlbumsQPushButton)
        self.synchronizeDialogPlaylistsQPushButton = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.synchronizeDialogPlaylistsQPushButton.sizePolicy().hasHeightForWidth())
        self.synchronizeDialogPlaylistsQPushButton.setSizePolicy(sizePolicy)
        self.synchronizeDialogPlaylistsQPushButton.setMinimumSize(QtCore.QSize(0, 33))
        self.synchronizeDialogPlaylistsQPushButton.setMaximumSize(QtCore.QSize(16777215, 33))
        self.synchronizeDialogPlaylistsQPushButton.setText("Playlists")
        self.synchronizeDialogPlaylistsQPushButton.setCheckable(True)
        self.synchronizeDialogPlaylistsQPushButton.setAutoExclusive(True)
        self.synchronizeDialogPlaylistsQPushButton.setAutoDefault(True)
        self.synchronizeDialogPlaylistsQPushButton.setObjectName("synchronizeDialogPlaylistsQPushButton")
        self.horizontalLayout_4.addWidget(self.synchronizeDialogPlaylistsQPushButton)
        self.synchronizeDialogAuthorsQPushButton = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.synchronizeDialogAuthorsQPushButton.sizePolicy().hasHeightForWidth())
        self.synchronizeDialogAuthorsQPushButton.setSizePolicy(sizePolicy)
        self.synchronizeDialogAuthorsQPushButton.setMinimumSize(QtCore.QSize(0, 33))
        self.synchronizeDialogAuthorsQPushButton.setMaximumSize(QtCore.QSize(16777215, 33))
        self.synchronizeDialogAuthorsQPushButton.setText("Authors")
        self.synchronizeDialogAuthorsQPushButton.setCheckable(True)
        self.synchronizeDialogAuthorsQPushButton.setAutoExclusive(True)
        self.synchronizeDialogAuthorsQPushButton.setObjectName("synchronizeDialogAuthorsQPushButton")
        self.horizontalLayout_4.addWidget(self.synchronizeDialogAuthorsQPushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_11.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(476, 329))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget.setObjectName("stackedWidget")
        self.synchronizeDialogSongsPage = QtWidgets.QWidget()
        self.synchronizeDialogSongsPage.setStyleSheet("#frame_9 QLabel{\n"
                                                      "    padding-left: 5px;\n"
                                                      "    color: white;\n"
                                                      "    font: 87 11pt \"Heebo Black\";    \n"
                                                      "}\n"
                                                      "\n"
                                                      "#scrollArea_4, #scrollArea_3 {\n"
                                                      "    border-radius: 4px;\n"
                                                      "    background-color: rgb(24, 24, 24);\n"
                                                      "}\n"
                                                      "#synchronizeDialogUploadSongsQWidget, #synchronizeDialogDownloadSongsQWidget{\n"
                                                      "    background-color: transparent;\n"
                                                      "}\n"
                                                      "#scrollArea_4 QPushButton{\n"
                                                      "    padding-left: 20px;\n"
                                                      "    text-align: left;\n"
                                                      "    font: 57 10pt \"Heebo Medium\";\n"
                                                      "    color: rgb(209, 103, 90);\n"
                                                      "}\n"
                                                      "#scrollArea_3 QPushButton{\n"
                                                      "    padding-left: 20px;\n"
                                                      "    text-align: left;\n"
                                                      "    font: 57 10pt \"Heebo Medium\";\n"
                                                      "    color: rgb(209, 103, 90);\n"
                                                      "}\n"
                                                      "#scrollArea_4 QPushButton:hover:!checked{\n"
                                                      "    color: rgb(255, 103, 90);\n"
                                                      "}\n"
                                                      "#scrollArea_3 QPushButton:hover:!checked{\n"
                                                      "    color: rgb(255, 103, 90);\n"
                                                      "}\n"
                                                      "#scrollArea_4 QPushButton:checked{\n"
                                                      "    padding-left: 0px;\n"
                                                      "    icon: url(:/icons/48x48/outlined/icons/48x48/outlined/outline_upload_lightgreen_48dp.png);\n"
                                                      "    color: rgb(84, 150, 81);\n"
                                                      "}\n"
                                                      "#scrollArea_4 QPushButton:hover:checked{\n"
                                                      "    color: rgb(84, 200, 81);\n"
                                                      "    icon: url(:/icons/48x48/outlined/icons/48x48/outlined/outline_upload_green_48dp.png);\n"
                                                      "}\n"
                                                      "#scrollArea_3 QPushButton:checked{\n"
                                                      "    padding-left: 0px;\n"
                                                      "    icon: url(:/icons/48x48/outlined/icons/48x48/outlined/outline_download_lightblue_48dp.png);\n"
                                                      "    color: rgb(88, 150, 166);\n"
                                                      "}\n"
                                                      "#scrollArea_3 QPushButton:hover:checked{\n"
                                                      "    color: rgb(0, 150, 202);\n"
                                                      "    icon: url(:/icons/48x48/outlined/icons/48x48/outlined/outline_download_blue_48dp.png);\n"
                                                      "}")
        self.synchronizeDialogSongsPage.setObjectName("synchronizeDialogSongsPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.synchronizeDialogSongsPage)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_9 = QtWidgets.QFrame(self.synchronizeDialogSongsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_9.setStyleSheet("")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_5.setContentsMargins(0, 10, 0, 10)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_9)
        self.label_4.setText("Download")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame_9)
        self.label_5.setText("Upload")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout_6.addWidget(self.frame_9)
        self.frame_11 = QtWidgets.QFrame(self.synchronizeDialogSongsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setMinimumSize(QtCore.QSize(233, 0))
        self.scrollArea_3.setMaximumSize(QtCore.QSize(233, 16777215))
        self.scrollArea_3.setStyleSheet("")
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.synchronizeDialogDownloadSongsQWidget = QtWidgets.QWidget()
        self.synchronizeDialogDownloadSongsQWidget.setGeometry(QtCore.QRect(0, 0, 233, 287))
        self.synchronizeDialogDownloadSongsQWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.synchronizeDialogDownloadSongsQWidget.setObjectName("synchronizeDialogDownloadSongsQWidget")
        self.synchronizeDialogDownloadSongsQVBoxLayout = QtWidgets.QVBoxLayout(self.synchronizeDialogDownloadSongsQWidget)
        self.synchronizeDialogDownloadSongsQVBoxLayout.setContentsMargins(5, 20, 20, 20)
        self.synchronizeDialogDownloadSongsQVBoxLayout.setSpacing(10)
        self.synchronizeDialogDownloadSongsQVBoxLayout.setObjectName("synchronizeDialogDownloadSongsQVBoxLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.synchronizeDialogDownloadSongsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_7.setText("PushButton")
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.synchronizeDialogDownloadSongsQVBoxLayout.addWidget(self.pushButton_7)
        self.pushButton_10 = QtWidgets.QPushButton(self.synchronizeDialogDownloadSongsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_10.setText("PushButton")
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setChecked(False)
        self.pushButton_10.setObjectName("pushButton_10")
        self.synchronizeDialogDownloadSongsQVBoxLayout.addWidget(self.pushButton_10, 0, QtCore.Qt.AlignLeft)
        self.pushButton_11 = QtWidgets.QPushButton(self.synchronizeDialogDownloadSongsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_11.setText("PushButton")
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.synchronizeDialogDownloadSongsQVBoxLayout.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.synchronizeDialogDownloadSongsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_12.setText("PushButton")
        self.pushButton_12.setCheckable(True)
        self.pushButton_12.setChecked(False)
        self.pushButton_12.setObjectName("pushButton_12")
        self.synchronizeDialogDownloadSongsQVBoxLayout.addWidget(self.pushButton_12)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.synchronizeDialogDownloadSongsQVBoxLayout.addItem(spacerItem2)
        self.scrollArea_3.setWidget(self.synchronizeDialogDownloadSongsQWidget)
        self.horizontalLayout_6.addWidget(self.scrollArea_3)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_4.sizePolicy().hasHeightForWidth())
        self.scrollArea_4.setSizePolicy(sizePolicy)
        self.scrollArea_4.setMinimumSize(QtCore.QSize(233, 0))
        self.scrollArea_4.setMaximumSize(QtCore.QSize(233, 16777215))
        self.scrollArea_4.setStyleSheet("")
        self.scrollArea_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.synchronizeDialogUploadSongsQWidget = QtWidgets.QWidget()
        self.synchronizeDialogUploadSongsQWidget.setGeometry(QtCore.QRect(0, 0, 233, 287))
        self.synchronizeDialogUploadSongsQWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.synchronizeDialogUploadSongsQWidget.setObjectName("synchronizeDialogUploadSongsQWidget")
        self.synchronizeDialogUploadSongsQVBoxLayout = QtWidgets.QVBoxLayout(self.synchronizeDialogUploadSongsQWidget)
        self.synchronizeDialogUploadSongsQVBoxLayout.setContentsMargins(5, 20, 20, 20)
        self.synchronizeDialogUploadSongsQVBoxLayout.setSpacing(10)
        self.synchronizeDialogUploadSongsQVBoxLayout.setObjectName("synchronizeDialogUploadSongsQVBoxLayout")
        self.pushButton_17 = QtWidgets.QPushButton(self.synchronizeDialogUploadSongsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_17.setText("PushButton")
        self.pushButton_17.setCheckable(True)
        self.pushButton_17.setObjectName("pushButton_17")
        self.synchronizeDialogUploadSongsQVBoxLayout.addWidget(self.pushButton_17)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.synchronizeDialogUploadSongsQVBoxLayout.addItem(spacerItem3)
        self.scrollArea_4.setWidget(self.synchronizeDialogUploadSongsQWidget)
        self.horizontalLayout_6.addWidget(self.scrollArea_4)
        self.verticalLayout_6.addWidget(self.frame_11)
        self.stackedWidget.addWidget(self.synchronizeDialogSongsPage)
        self.synchronizeDialogAlbumsPage = QtWidgets.QWidget()
        self.synchronizeDialogAlbumsPage.setStyleSheet("#frame_12 QLabel{\n"
                                                       "    padding-left: 5px;\n"
                                                       "    color: white;\n"
                                                       "    font: 87 11pt \"Heebo Black\";    \n"
                                                       "}\n"
                                                       "#scrollArea_6, #scrollArea_5{\n"
                                                       "    border-radius: 4px;\n"
                                                       "    background-color: rgb(24, 24, 24);\n"
                                                       "}\n"
                                                       "#synchronizeDialogUploadAlbumsQWidget, #synchronizeDialogDownloadAlbumsQWidget{\n"
                                                       "    background-color: transparent;\n"
                                                       "}\n"
                                                       "#scrollArea_6 QPushButton{\n"
                                                       "    padding-left: 20px;\n"
                                                       "    text-align: left;\n"
                                                       "    font: 57 10pt \"Heebo Medium\";\n"
                                                       "    color: rgb(209, 103, 90);\n"
                                                       "}\n"
                                                       "#scrollArea_5 QPushButton{\n"
                                                       "    padding-left: 20px;\n"
                                                       "    text-align: left;\n"
                                                       "    font: 57 10pt \"Heebo Medium\";\n"
                                                       "    color: rgb(209, 103, 90);\n"
                                                       "}\n"
                                                       "#scrollArea_6 QPushButton:hover:!checked{\n"
                                                       "    color: rgb(255, 103, 90);\n"
                                                       "}\n"
                                                       "#scrollArea_5 QPushButton:hover:!checked{\n"
                                                       "    color: rgb(255, 103, 90);\n"
                                                       "}\n"
                                                       "#scrollArea_6 QPushButton:checked{\n"
                                                       "    padding-left: 0px;\n"
                                                       "    icon: url(:/icons/48x48/outlined/icons/48x48/outlined/outline_upload_lightgreen_48dp.png);\n"
                                                       "    color: rgb(84, 150, 81);\n"
                                                       "}\n"
                                                       "#scrollArea_6 QPushButton:hover:checked{\n"
                                                       "    color: rgb(84, 200, 81);\n"
                                                       "    icon: url(:/icons/48x48/outlined/icons/48x48/outlined/outline_upload_green_48dp.png);\n"
                                                       "}\n"
                                                       "#scrollArea_5 QPushButton:checked{\n"
                                                       "    padding-left: 0px;\n"
                                                       "    icon: url(:/icons/48x48/outlined/icons/48x48/outlined/outline_download_lightblue_48dp.png);\n"
                                                       "    color: rgb(88, 150, 166);\n"
                                                       "}\n"
                                                       "#scrollArea_5 QPushButton:hover:checked{\n"
                                                       "    color: rgb(0, 150, 202);\n"
                                                       "    icon: url(:/icons/48x48/outlined/icons/48x48/outlined/outline_download_blue_48dp.png);\n"
                                                       "}")
        self.synchronizeDialogAlbumsPage.setObjectName("synchronizeDialogAlbumsPage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.synchronizeDialogAlbumsPage)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_12 = QtWidgets.QFrame(self.synchronizeDialogAlbumsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_7.setContentsMargins(0, 10, 0, 10)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.frame_12)
        self.label_6.setText("Download")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_12)
        self.label_7.setText("Upload")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.verticalLayout_7.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.synchronizeDialogAlbumsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_5.sizePolicy().hasHeightForWidth())
        self.scrollArea_5.setSizePolicy(sizePolicy)
        self.scrollArea_5.setMinimumSize(QtCore.QSize(233, 0))
        self.scrollArea_5.setMaximumSize(QtCore.QSize(233, 16777215))
        self.scrollArea_5.setStyleSheet("")
        self.scrollArea_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.synchronizeDialogDownloadAlbumsQWidget = QtWidgets.QWidget()
        self.synchronizeDialogDownloadAlbumsQWidget.setGeometry(QtCore.QRect(0, 0, 233, 287))
        self.synchronizeDialogDownloadAlbumsQWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.synchronizeDialogDownloadAlbumsQWidget.setObjectName("synchronizeDialogDownloadAlbumsQWidget")
        self.synchronizeDialogDownloadAlbumsQVBoxLayout = QtWidgets.QVBoxLayout(self.synchronizeDialogDownloadAlbumsQWidget)
        self.synchronizeDialogDownloadAlbumsQVBoxLayout.setContentsMargins(5, 20, 20, 20)
        self.synchronizeDialogDownloadAlbumsQVBoxLayout.setSpacing(10)
        self.synchronizeDialogDownloadAlbumsQVBoxLayout.setObjectName("synchronizeDialogDownloadAlbumsQVBoxLayout")
        self.pushButton_14 = QtWidgets.QPushButton(self.synchronizeDialogDownloadAlbumsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_14.setText("PushButton")
        self.pushButton_14.setCheckable(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.synchronizeDialogDownloadAlbumsQVBoxLayout.addWidget(self.pushButton_14)
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.synchronizeDialogDownloadAlbumsQVBoxLayout.addItem(spacerItem4)
        self.scrollArea_5.setWidget(self.synchronizeDialogDownloadAlbumsQWidget)
        self.horizontalLayout_8.addWidget(self.scrollArea_5)
        self.scrollArea_6 = QtWidgets.QScrollArea(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_6.sizePolicy().hasHeightForWidth())
        self.scrollArea_6.setSizePolicy(sizePolicy)
        self.scrollArea_6.setMinimumSize(QtCore.QSize(233, 0))
        self.scrollArea_6.setMaximumSize(QtCore.QSize(233, 16777215))
        self.scrollArea_6.setStyleSheet("")
        self.scrollArea_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.synchronizeDialogUploadAlbumsQWidget = QtWidgets.QWidget()
        self.synchronizeDialogUploadAlbumsQWidget.setGeometry(QtCore.QRect(0, 0, 233, 287))
        self.synchronizeDialogUploadAlbumsQWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.synchronizeDialogUploadAlbumsQWidget.setObjectName("synchronizeDialogUploadAlbumsQWidget")
        self.synchronizeDialogUploadAlbumsQVBoxLayout = QtWidgets.QVBoxLayout(self.synchronizeDialogUploadAlbumsQWidget)
        self.synchronizeDialogUploadAlbumsQVBoxLayout.setContentsMargins(5, 20, 20, 20)
        self.synchronizeDialogUploadAlbumsQVBoxLayout.setSpacing(10)
        self.synchronizeDialogUploadAlbumsQVBoxLayout.setObjectName("synchronizeDialogUploadAlbumsQVBoxLayout")
        self.pushButton_19 = QtWidgets.QPushButton(self.synchronizeDialogUploadAlbumsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_19.setText("PushButton")
        self.pushButton_19.setCheckable(True)
        self.pushButton_19.setObjectName("pushButton_19")
        self.synchronizeDialogUploadAlbumsQVBoxLayout.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.synchronizeDialogUploadAlbumsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setText("PushButton")
        self.pushButton_20.setCheckable(True)
        self.pushButton_20.setChecked(False)
        self.pushButton_20.setObjectName("pushButton_20")
        self.synchronizeDialogUploadAlbumsQVBoxLayout.addWidget(self.pushButton_20)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.synchronizeDialogUploadAlbumsQVBoxLayout.addItem(spacerItem5)
        self.scrollArea_6.setWidget(self.synchronizeDialogUploadAlbumsQWidget)
        self.horizontalLayout_8.addWidget(self.scrollArea_6)
        self.verticalLayout_7.addWidget(self.frame_13)
        self.stackedWidget.addWidget(self.synchronizeDialogAlbumsPage)
        self.synchronizeDialogPlaylistsPage = QtWidgets.QWidget()
        self.synchronizeDialogPlaylistsPage.setStyleSheet("#frame_14 QLabel{\n"
                                                          "    padding-left: 5px;\n"
                                                          "    color: white;\n"
                                                          "    font: 87 11pt \"Heebo Black\";    \n"
                                                          "}\n"
                                                          "#scrollArea_8, #scrollArea_7{\n"
                                                          "    border-radius: 4px;\n"
                                                          "    background-color: rgb(24, 24, 24);\n"
                                                          "}\n"
                                                          "#synchronizeDialogUploadPlaylistsQWidget, #synchronizeDialogDownloadPlaylistsQWidget{\n"
                                                          "    background-color: transparent;\n"
                                                          "}\n"
                                                          "#scrollArea_8 QPushButton{\n"
                                                          "    padding-left: 20px;\n"
                                                          "    text-align: left;\n"
                                                          "    font: 57 10pt \"Heebo Medium\";\n"
                                                          "    color: rgb(209, 103, 90);\n"
                                                          "}\n"
                                                          "#scrollArea_7 QPushButton{\n"
                                                          "    padding-left: 20px;\n"
                                                          "    text-align: left;\n"
                                                          "    font: 57 10pt \"Heebo Medium\";\n"
                                                          "    color: rgb(209, 103, 90);\n"
                                                          "}\n"
                                                          "#scrollArea_8 QPushButton:hover:!checked{\n"
                                                          "    color: rgb(255, 103, 90);\n"
                                                          "}\n"
                                                          "#scrollArea_7 QPushButton:hover:!checked{\n"
                                                          "    color: rgb(255, 103, 90);\n"
                                                          "}\n"
                                                          "#scrollArea_8 QPushButton:checked{\n"
                                                          "    padding-left: 0px;\n"
                                                          "    icon: url(:/icons/48x48/outlined/icons/48x48/outlined/outline_upload_lightgreen_48dp.png);\n"
                                                          "    color: rgb(84, 150, 81);\n"
                                                          "}\n"
                                                          "#scrollArea_8 QPushButton:hover:checked{\n"
                                                          "    color: rgb(84, 200, 81);\n"
                                                          "    icon: url(:/icons/48x48/outlined/icons/48x48/outlined/outline_upload_green_48dp.png);\n"
                                                          "}\n"
                                                          "#scrollArea_7 QPushButton:checked{\n"
                                                          "    padding-left: 0px;\n"
                                                          "    icon: url(:/icons/48x48/outlined/icons/48x48/outlined/outline_download_lightblue_48dp.png);\n"
                                                          "    color: rgb(88, 150, 166);\n"
                                                          "}\n"
                                                          "#scrollArea_7 QPushButton:hover:checked{\n"
                                                          "    color: rgb(0, 150, 202);\n"
                                                          "    icon: url(:/icons/48x48/outlined/icons/48x48/outlined/outline_download_blue_48dp.png);\n"
                                                          "}")
        self.synchronizeDialogPlaylistsPage.setObjectName("synchronizeDialogPlaylistsPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.synchronizeDialogPlaylistsPage)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_14 = QtWidgets.QFrame(self.synchronizeDialogPlaylistsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_14.setStyleSheet("")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_9.setContentsMargins(0, 10, 0, 10)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.frame_14)
        self.label_8.setText("Download")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.frame_14)
        self.label_9.setText("Upload")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.verticalLayout_9.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.synchronizeDialogPlaylistsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.scrollArea_7 = QtWidgets.QScrollArea(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_7.sizePolicy().hasHeightForWidth())
        self.scrollArea_7.setSizePolicy(sizePolicy)
        self.scrollArea_7.setMinimumSize(QtCore.QSize(233, 0))
        self.scrollArea_7.setMaximumSize(QtCore.QSize(233, 16777215))
        self.scrollArea_7.setStyleSheet("")
        self.scrollArea_7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.synchronizeDialogDownloadPlaylistsQWidget = QtWidgets.QWidget()
        self.synchronizeDialogDownloadPlaylistsQWidget.setGeometry(QtCore.QRect(0, 0, 233, 287))
        self.synchronizeDialogDownloadPlaylistsQWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.synchronizeDialogDownloadPlaylistsQWidget.setObjectName("synchronizeDialogDownloadPlaylistsQWidget")
        self.synchronizeDialogDownloadPlaylistsQVBoxLayout = QtWidgets.QVBoxLayout(self.synchronizeDialogDownloadPlaylistsQWidget)
        self.synchronizeDialogDownloadPlaylistsQVBoxLayout.setContentsMargins(5, 20, 20, 20)
        self.synchronizeDialogDownloadPlaylistsQVBoxLayout.setSpacing(10)
        self.synchronizeDialogDownloadPlaylistsQVBoxLayout.setObjectName("synchronizeDialogDownloadPlaylistsQVBoxLayout")
        self.pushButton_21 = QtWidgets.QPushButton(self.synchronizeDialogDownloadPlaylistsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy)
        self.pushButton_21.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_21.setText("PushButton")
        self.pushButton_21.setCheckable(True)
        self.pushButton_21.setObjectName("pushButton_21")
        self.synchronizeDialogDownloadPlaylistsQVBoxLayout.addWidget(self.pushButton_21)
        self.pushButton_24 = QtWidgets.QPushButton(self.synchronizeDialogDownloadPlaylistsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_24.sizePolicy().hasHeightForWidth())
        self.pushButton_24.setSizePolicy(sizePolicy)
        self.pushButton_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_24.setText("PushButton")
        self.pushButton_24.setCheckable(True)
        self.pushButton_24.setChecked(False)
        self.pushButton_24.setObjectName("pushButton_24")
        self.synchronizeDialogDownloadPlaylistsQVBoxLayout.addWidget(self.pushButton_24)
        spacerItem6 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.synchronizeDialogDownloadPlaylistsQVBoxLayout.addItem(spacerItem6)
        self.scrollArea_7.setWidget(self.synchronizeDialogDownloadPlaylistsQWidget)
        self.horizontalLayout_10.addWidget(self.scrollArea_7)
        self.scrollArea_8 = QtWidgets.QScrollArea(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_8.sizePolicy().hasHeightForWidth())
        self.scrollArea_8.setSizePolicy(sizePolicy)
        self.scrollArea_8.setMinimumSize(QtCore.QSize(233, 0))
        self.scrollArea_8.setMaximumSize(QtCore.QSize(233, 16777215))
        self.scrollArea_8.setStyleSheet("")
        self.scrollArea_8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollArea_8.setObjectName("scrollArea_8")
        self.synchronizeDialogUploadPlaylistsQWidget = QtWidgets.QWidget()
        self.synchronizeDialogUploadPlaylistsQWidget.setGeometry(QtCore.QRect(0, 0, 233, 287))
        self.synchronizeDialogUploadPlaylistsQWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.synchronizeDialogUploadPlaylistsQWidget.setObjectName("synchronizeDialogUploadPlaylistsQWidget")
        self.synchronizeDialogUploadPlaylistsQVBoxLayout = QtWidgets.QVBoxLayout(self.synchronizeDialogUploadPlaylistsQWidget)
        self.synchronizeDialogUploadPlaylistsQVBoxLayout.setContentsMargins(5, 20, 20, 20)
        self.synchronizeDialogUploadPlaylistsQVBoxLayout.setSpacing(10)
        self.synchronizeDialogUploadPlaylistsQVBoxLayout.setObjectName("synchronizeDialogUploadPlaylistsQVBoxLayout")
        self.pushButton_25 = QtWidgets.QPushButton(self.synchronizeDialogUploadPlaylistsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_25.sizePolicy().hasHeightForWidth())
        self.pushButton_25.setSizePolicy(sizePolicy)
        self.pushButton_25.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_25.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_25.setText("PushButton")
        self.pushButton_25.setCheckable(True)
        self.pushButton_25.setObjectName("pushButton_25")
        self.synchronizeDialogUploadPlaylistsQVBoxLayout.addWidget(self.pushButton_25)
        self.pushButton_26 = QtWidgets.QPushButton(self.synchronizeDialogUploadPlaylistsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_26.sizePolicy().hasHeightForWidth())
        self.pushButton_26.setSizePolicy(sizePolicy)
        self.pushButton_26.setText("PushButton")
        self.pushButton_26.setCheckable(True)
        self.pushButton_26.setChecked(False)
        self.pushButton_26.setObjectName("pushButton_26")
        self.synchronizeDialogUploadPlaylistsQVBoxLayout.addWidget(self.pushButton_26)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.synchronizeDialogUploadPlaylistsQVBoxLayout.addItem(spacerItem7)
        self.scrollArea_8.setWidget(self.synchronizeDialogUploadPlaylistsQWidget)
        self.horizontalLayout_10.addWidget(self.scrollArea_8)
        self.verticalLayout_9.addWidget(self.frame_15)
        self.stackedWidget.addWidget(self.synchronizeDialogPlaylistsPage)
        self.synchronizeDialogAuthorsPage = QtWidgets.QWidget()
        self.synchronizeDialogAuthorsPage.setStyleSheet("#frame_16 QLabel{\n"
                                                        "    padding-left: 5px;\n"
                                                        "    color: white;\n"
                                                        "    font: 87 11pt \"Heebo Black\";    \n"
                                                        "}\n"
                                                        "#scrollArea_9 QPushButton{\n"
                                                        "    padding-left: 20px;\n"
                                                        "    text-align: left;\n"
                                                        "    font: 57 10pt \"Heebo Medium\";\n"
                                                        "    color: rgb(179, 179, 179);\n"
                                                        "}\n"
                                                        "#scrollArea_9 QPushButton:hover:!checked{\n"
                                                        "    color: white;\n"
                                                        "}\n"
                                                        "#scrollArea_10, #scrollArea_9{\n"
                                                        "    border-radius: 4px;\n"
                                                        "    background-color: rgb(24, 24, 24);\n"
                                                        "}\n"
                                                        "#synchronizeDialogUploadAuthorsQWidget, #synchronizeDialogDownloadAuthorsQWidget{\n"
                                                        "    background-color: transparent;\n"
                                                        "}\n"
                                                        "#scrollArea_10 QPushButton{\n"
                                                        "    padding-left: 20px;\n"
                                                        "    text-align: left;\n"
                                                        "    font: 57 10pt \"Heebo Medium\";\n"
                                                        "    color: rgb(209, 103, 90);\n"
                                                        "}\n"
                                                        "#scrollArea_9 QPushButton{\n"
                                                        "    padding-left: 20px;\n"
                                                        "    text-align: left;\n"
                                                        "    font: 57 10pt \"Heebo Medium\";\n"
                                                        "    color: rgb(209, 103, 90);\n"
                                                        "}\n"
                                                        "#scrollArea_10 QPushButton:hover:!checked{\n"
                                                        "    color: rgb(255, 103, 90);\n"
                                                        "}\n"
                                                        "#scrollArea_9 QPushButton:hover:!checked{\n"
                                                        "    color: rgb(255, 103, 90);\n"
                                                        "}\n"
                                                        "#scrollArea_10 QPushButton:checked{\n"
                                                        "    padding-left: 0px;\n"
                                                        "    icon: url(:/icons/48x48/outlined/icons/48x48/outlined/outline_upload_lightgreen_48dp.png);\n"
                                                        "    color: rgb(84, 150, 81);\n"
                                                        "}\n"
                                                        "#scrollArea_10 QPushButton:hover:checked{\n"
                                                        "    color: rgb(84, 200, 81);\n"
                                                        "    icon: url(:/icons/48x48/outlined/icons/48x48/outlined/outline_upload_green_48dp.png);\n"
                                                        "}\n"
                                                        "#scrollArea_9 QPushButton:checked{\n"
                                                        "    padding-left: 0px;\n"
                                                        "    icon: url(:/icons/48x48/outlined/icons/48x48/outlined/outline_download_lightblue_48dp.png);\n"
                                                        "    color: rgb(88, 150, 166);\n"
                                                        "}\n"
                                                        "#scrollArea_9 QPushButton:hover:checked{\n"
                                                        "    color: rgb(0, 150, 202);\n"
                                                        "    icon: url(:/icons/48x48/outlined/icons/48x48/outlined/outline_download_blue_48dp.png);\n"
                                                        "}")
        self.synchronizeDialogAuthorsPage.setObjectName("synchronizeDialogAuthorsPage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.synchronizeDialogAuthorsPage)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_16 = QtWidgets.QFrame(self.synchronizeDialogAuthorsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_16.setStyleSheet("")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_11.setContentsMargins(0, 10, 0, 10)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.frame_16)
        self.label_10.setText("Download")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.frame_16)
        self.label_11.setText("Upload")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.verticalLayout_10.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.synchronizeDialogAuthorsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.scrollArea_9 = QtWidgets.QScrollArea(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_9.sizePolicy().hasHeightForWidth())
        self.scrollArea_9.setSizePolicy(sizePolicy)
        self.scrollArea_9.setMinimumSize(QtCore.QSize(233, 0))
        self.scrollArea_9.setMaximumSize(QtCore.QSize(233, 16777215))
        self.scrollArea_9.setStyleSheet("")
        self.scrollArea_9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_9.setWidgetResizable(True)
        self.scrollArea_9.setObjectName("scrollArea_9")
        self.synchronizeDialogDownloadAuthorsQWidget = QtWidgets.QWidget()
        self.synchronizeDialogDownloadAuthorsQWidget.setGeometry(QtCore.QRect(0, 0, 233, 287))
        self.synchronizeDialogDownloadAuthorsQWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.synchronizeDialogDownloadAuthorsQWidget.setObjectName("synchronizeDialogDownloadAuthorsQWidget")
        self.synchronizeDialogDownloadAuthorsQVBoxLayout = QtWidgets.QVBoxLayout(self.synchronizeDialogDownloadAuthorsQWidget)
        self.synchronizeDialogDownloadAuthorsQVBoxLayout.setContentsMargins(5, 20, 20, 20)
        self.synchronizeDialogDownloadAuthorsQVBoxLayout.setSpacing(10)
        self.synchronizeDialogDownloadAuthorsQVBoxLayout.setObjectName("synchronizeDialogDownloadAuthorsQVBoxLayout")
        self.pushButton_27 = QtWidgets.QPushButton(self.synchronizeDialogDownloadAuthorsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_27.sizePolicy().hasHeightForWidth())
        self.pushButton_27.setSizePolicy(sizePolicy)
        self.pushButton_27.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_27.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_27.setText("PushButton")
        self.pushButton_27.setCheckable(True)
        self.pushButton_27.setObjectName("pushButton_27")
        self.synchronizeDialogDownloadAuthorsQVBoxLayout.addWidget(self.pushButton_27)
        self.pushButton_28 = QtWidgets.QPushButton(self.synchronizeDialogDownloadAuthorsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_28.sizePolicy().hasHeightForWidth())
        self.pushButton_28.setSizePolicy(sizePolicy)
        self.pushButton_28.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_28.setText("PushButton")
        self.pushButton_28.setCheckable(True)
        self.pushButton_28.setChecked(False)
        self.pushButton_28.setObjectName("pushButton_28")
        self.synchronizeDialogDownloadAuthorsQVBoxLayout.addWidget(self.pushButton_28, 0, QtCore.Qt.AlignLeft)
        self.pushButton_30 = QtWidgets.QPushButton(self.synchronizeDialogDownloadAuthorsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_30.sizePolicy().hasHeightForWidth())
        self.pushButton_30.setSizePolicy(sizePolicy)
        self.pushButton_30.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_30.setText("PushButton")
        self.pushButton_30.setCheckable(True)
        self.pushButton_30.setChecked(False)
        self.pushButton_30.setObjectName("pushButton_30")
        self.synchronizeDialogDownloadAuthorsQVBoxLayout.addWidget(self.pushButton_30)
        spacerItem8 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.synchronizeDialogDownloadAuthorsQVBoxLayout.addItem(spacerItem8)
        self.scrollArea_9.setWidget(self.synchronizeDialogDownloadAuthorsQWidget)
        self.horizontalLayout_12.addWidget(self.scrollArea_9)
        self.scrollArea_10 = QtWidgets.QScrollArea(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_10.sizePolicy().hasHeightForWidth())
        self.scrollArea_10.setSizePolicy(sizePolicy)
        self.scrollArea_10.setMinimumSize(QtCore.QSize(233, 0))
        self.scrollArea_10.setMaximumSize(QtCore.QSize(233, 16777215))
        self.scrollArea_10.setStyleSheet("")
        self.scrollArea_10.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_10.setWidgetResizable(True)
        self.scrollArea_10.setObjectName("scrollArea_10")
        self.synchronizeDialogUploadAuthorsQWidget = QtWidgets.QWidget()
        self.synchronizeDialogUploadAuthorsQWidget.setGeometry(QtCore.QRect(0, 0, 233, 287))
        self.synchronizeDialogUploadAuthorsQWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.synchronizeDialogUploadAuthorsQWidget.setObjectName("synchronizeDialogUploadAuthorsQWidget")
        self.synchronizeDialogUploadAuthorsQVBoxLayout = QtWidgets.QVBoxLayout(self.synchronizeDialogUploadAuthorsQWidget)
        self.synchronizeDialogUploadAuthorsQVBoxLayout.setContentsMargins(5, 20, 20, 20)
        self.synchronizeDialogUploadAuthorsQVBoxLayout.setSpacing(10)
        self.synchronizeDialogUploadAuthorsQVBoxLayout.setObjectName("synchronizeDialogUploadAuthorsQVBoxLayout")
        self.pushButton_31 = QtWidgets.QPushButton(self.synchronizeDialogUploadAuthorsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_31.sizePolicy().hasHeightForWidth())
        self.pushButton_31.setSizePolicy(sizePolicy)
        self.pushButton_31.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_31.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_31.setText("PushButton")
        self.pushButton_31.setCheckable(True)
        self.pushButton_31.setObjectName("pushButton_31")
        self.synchronizeDialogUploadAuthorsQVBoxLayout.addWidget(self.pushButton_31)
        self.pushButton_32 = QtWidgets.QPushButton(self.synchronizeDialogUploadAuthorsQWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_32.sizePolicy().hasHeightForWidth())
        self.pushButton_32.setSizePolicy(sizePolicy)
        self.pushButton_32.setText("PushButton")
        self.pushButton_32.setCheckable(True)
        self.pushButton_32.setChecked(False)
        self.pushButton_32.setObjectName("pushButton_32")
        self.synchronizeDialogUploadAuthorsQVBoxLayout.addWidget(self.pushButton_32)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.synchronizeDialogUploadAuthorsQVBoxLayout.addItem(spacerItem9)
        self.scrollArea_10.setWidget(self.synchronizeDialogUploadAuthorsQWidget)
        self.horizontalLayout_12.addWidget(self.scrollArea_10)
        self.verticalLayout_10.addWidget(self.frame_17)
        self.stackedWidget.addWidget(self.synchronizeDialogAuthorsPage)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.verticalLayout_11.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("PlaylistSortButtonsQFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_2.setContentsMargins(0, 16, 1, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem10 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.synchronizeDialogSynchronizeButton = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.synchronizeDialogSynchronizeButton.sizePolicy().hasHeightForWidth())
        self.synchronizeDialogSynchronizeButton.setSizePolicy(sizePolicy)
        self.synchronizeDialogSynchronizeButton.setMinimumSize(QtCore.QSize(90, 32))
        self.synchronizeDialogSynchronizeButton.setMaximumSize(QtCore.QSize(90, 32))
        font = QtGui.QFont()
        font.setFamily("Heebo Medium")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        font.setKerning(True)
        self.synchronizeDialogSynchronizeButton.setFont(font)
        self.synchronizeDialogSynchronizeButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.synchronizeDialogSynchronizeButton.setStyleSheet("")
        self.synchronizeDialogSynchronizeButton.setText("Synchronize")
        self.synchronizeDialogSynchronizeButton.setObjectName("synchronizeDialogSynchronizeButton")
        self.verticalLayout_8.addWidget(self.synchronizeDialogSynchronizeButton)
        self.horizontalLayout_2.addWidget(self.frame_10)
        self.verticalLayout_11.addWidget(self.frame_8)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame_3)
        self.stackedWidget.setCurrentIndex(0)

    def set_synchronize_dialog_stacked_widget_index(self, index):
        """Set synchronizeDialog's stacked widget's index to specified value:

        Parameters:
            index(int): value to change synchronizeDialog's stacked widget index to
        """
        self.stackedWidget.setCurrentIndex(index)